# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('age', models.SmallIntegerField(null=True)),
                ('tel', models.CharField(max_length=32, null=True)),
                ('passwd', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
