# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=512, null=True)),
                ('content', models.TextField(null=True)),
                ('publish_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
